# Generated by Django 5.0.7 on 2024-07-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
    ]
