# Generated by Django 5.0.7 on 2024-07-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_author_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='auther_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='auther_id',
            field=models.ManyToManyField(related_name='blogs', to='blogs.author'),
        ),
    ]
