# Generated by Django 5.0.7 on 2024-07-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_author_image_blog_image_delete_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
