# Generated by Django 5.0.7 on 2024-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Middle ', 'Middle'), ('Senior', 'Senior'), ('Expert', 'Expert')], default='Junior', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
