# Generated by Django 5.0.7 on 2024-07-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_address_teacher_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
