# Generated by Django 5.0.7 on 2024-07-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_name_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
