# Generated by Django 5.0.7 on 2024-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_image_course_image_alter_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
